# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nestor-QA
email: 
description: > # this means to ignore newlines until "baseurl:"
  Nestor-QA is an Open Source test management software
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nestor-qa.org" # the base hostname & protocol for your site
twitter_username: qanestor
github_username:  nestor-qa

# Build settings
markdown: kramdown
